log4r_config:
  # define all pre config ...
  pre_config:
    custom_levels:
      - DEBUG
      - DEBUG_FINE
      - DEBUG_MEDIUM
      - DEBUG_GROSS
      - DETAIL
      - INFO
      - WARN
      - ALARM
      - ERROR
      - FATAL
    global:
      level: INFO
    root  :
      level: INFO

  # define all loggers ...
  loggers:
    - name      : Af
      level     : DETAIL
      outputters:
        - stdout

    - name      : Process
      level     : DEBUG
      outputters:
        - stdout

  # define all outputters (incl. formatters)
  outputters:
    - type     : StdoutOutputter
      name     : stdout
      level    : DEBUG
      formatter:
        date_pattern: '%y%m%d %H:%M:%S.%L'
        pattern     : '%d %p %C %l %M'
        type        : PatternFormatter
